# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-26 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Postavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
                ('enota_mere', models.CharField(max_length=10)),
                ('dela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.Dela')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VrstaDel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
                ('skupina_del', models.CharField(choices=[('GR', 'Gradbena dela'), ('OB', 'Obrtniška dela')], default='GR', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dela',
            name='vrsta_del',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.VrstaDel'),
        ),
    ]
