# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-21 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(null=True)),
                ('koda', models.CharField(max_length=100, null=True)),
                ('opis', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Postavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(null=True)),
                ('koda', models.CharField(max_length=100, null=True)),
                ('opis', models.CharField(max_length=100)),
                ('enota_mere', models.CharField(max_length=10)),
                ('dela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifikacije.Dela')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PredmetSpecifikacije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(null=True)),
                ('koda', models.CharField(max_length=100, null=True)),
                ('opis', models.CharField(max_length=100)),
                ('postavka', models.ManyToManyField(to='specifikacije.Postavka')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specifikacija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(null=True)),
                ('koda', models.CharField(max_length=100, null=True)),
                ('opis', models.CharField(max_length=100)),
                ('osnova_specifikacije', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifikacije.PredmetSpecifikacije')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
