# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-28 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specifikacije', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlasifikacijaSpecifikacije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
                ('podrocje', models.CharField(max_length=100)),
                ('podrobnosti', models.CharField(max_length=100)),
                ('vrsta', models.CharField(choices=[('Lastnosti materialov', 'Lastnosti materialov'), ('PD', 'Pogoji dela'), ('LI', 'Delovni postopki'), ('PI', 'Lastnosti izdelka'), ('VZ', 'Varnostne zahteve')], default='Lastnosti materialov', max_length=10)),
                ('osnova', models.CharField(choices=[('Zakonodaja', 'Zakonodaja'), ('Pravila stroke', 'Pravila stroke'), ('Smernice', 'Smernice')], default='Pravila stroke', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='podrocjespecifikacije',
            name='dokumentacija',
        ),
        migrations.RemoveField(
            model_name='specifikacija',
            name='podrocje_specifikacije',
        ),
        migrations.AlterField(
            model_name='dokumentacija',
            name='vrsta_dokumenta',
            field=models.CharField(choices=[('Standard', 'Standard'), ('SM', 'Smernice'), ('SL', 'Strokovna literatura')], default='Standard', max_length=10),
        ),
        migrations.DeleteModel(
            name='PodrocjeSpecifikacije',
        ),
        migrations.AddField(
            model_name='klasifikacijaspecifikacije',
            name='dokumentacija',
            field=models.ManyToManyField(to='specifikacije.Dokumentacija'),
        ),
        migrations.AddField(
            model_name='specifikacija',
            name='klasifikacija_specifikacije',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifikacije.KlasifikacijaSpecifikacije'),
        ),
    ]
