# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-21 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specifikacije', '0003_auto_20171221_1015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredmetSpecifikacije',
            new_name='KriterijSpecifikacije',
        ),
        migrations.RenameField(
            model_name='specifikacija',
            old_name='predmet',
            new_name='kriterij',
        ),
    ]
